/* 🤖 this file was generated by svg-to-ts */
export const baseIconsClosedEye: {
  name: 'closed_eye';
  data: string;
} = {
  name: 'closed_eye',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4.5 3.75L19.5 20.25" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M14.5225 14.7751C13.8343 15.4055 12.9339 15.7536 12.0006 15.7501C11.2437 15.75 10.5046 15.5209 9.88033 15.0929C9.2561 14.6649 8.776 14.058 8.50314 13.352C8.23028 12.646 8.17744 11.874 8.35156 11.1374C8.52568 10.4008 8.91861 9.73418 9.4787 9.2251" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M6.9375 6.43115C3.1125 8.3624 1.5 11.9999 1.5 11.9999C1.5 11.9999 4.5 18.7499 12 18.7499C13.7574 18.7642 15.4929 18.3593 17.0625 17.5687" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M19.556 15.8531C21.5997 14.025 22.4997 12 22.4997 12C22.4997 12 19.4997 5.25002 11.9997 5.25002C11.3495 5.24874 10.7004 5.30205 10.0591 5.4094" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M12.7031 8.31543C13.5006 8.46653 14.2273 8.87293 14.7735 9.47329C15.3198 10.0736 15.6559 10.8354 15.7313 11.6436" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const baseIconsOpenedEye: {
  name: 'opened_eye';
  data: string;
} = {
  name: 'opened_eye',
  data: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 5.25C4.5 5.25 1.5 12 1.5 12C1.5 12 4.5 18.75 12 18.75C19.5 18.75 22.5 12 22.5 12C22.5 12 19.5 5.25 12 5.25Z" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/><path d="M12 15.75C14.0711 15.75 15.75 14.0711 15.75 12C15.75 9.92893 14.0711 8.25 12 8.25C9.92893 8.25 8.25 9.92893 8.25 12C8.25 14.0711 9.92893 15.75 12 15.75Z" stroke="#989898" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
};
export const baseIconsWarningIcon: {
  name: 'warning_icon';
  data: string;
} = {
  name: 'warning_icon',
  data: `<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8 14C11.3137 14 14 11.3137 14 8C14 4.68629 11.3137 2 8 2C4.68629 2 2 4.68629 2 8C2 11.3137 4.68629 14 8 14Z" stroke="#DD1C1C" stroke-miterlimit="10"/><path d="M8 5V8.5" stroke="#DD1C1C" stroke-linecap="round" stroke-linejoin="round"/><path d="M8.25 10.75C8.25 10.8881 8.13807 11 8 11C7.86193 11 7.75 10.8881 7.75 10.75C7.75 10.6119 7.86193 10.5 8 10.5C8.13807 10.5 8.25 10.6119 8.25 10.75Z" fill="#DD1C1C" stroke="#DD1C1C"/></svg>`,
};
export type baseIcon = 'closed_eye' | 'opened_eye' | 'warning_icon';
export interface BaseIcon {
  name: baseIcon;
  data: string;
}
export type BaseIconNameSubset<T extends Readonly<BaseIcon[]>> =
  T[number]['name'];
export const completeIconSet = [
  baseIconsClosedEye,
  baseIconsOpenedEye,
  baseIconsWarningIcon,
];
